# Generated by Django 4.2.5 on 2024-10-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_ispublished_alter_movies_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='isHome',
            field=models.BooleanField(default=False),
        ),
    ]
